<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'HS',
  'author' => 'Julián Andrés Galvis',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'hyspainting',
  'published_date' => '2024-02-22 17:30:35',
  'type' => 'module',
  'version' => 1708623036,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'hyspainting',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'HS_Facturador',
      'class' => 'HS_Facturador',
      'path' => 'modules/HS_Facturador/HS_Facturador.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'HS_Facturador_proyectos',
      'class' => 'HS_Facturador_proyectos',
      'path' => 'modules/HS_Facturador_proyectos/HS_Facturador_proyectos.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'HS_inventarios',
      'class' => 'HS_inventarios',
      'path' => 'modules/HS_inventarios/HS_inventarios.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'HS_Prestamos',
      'class' => 'HS_Prestamos',
      'path' => 'modules/HS_Prestamos/HS_Prestamos.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'HS_Programador',
      'class' => 'HS_Programador',
      'path' => 'modules/HS_Programador/HS_Programador.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'HS_Registro_horas',
      'class' => 'HS_Registro_horas',
      'path' => 'modules/HS_Registro_horas/HS_Registro_horas.php',
      'tab' => true,
    ),
    6 => 
    array (
      'module' => 'HS_Reportes_personalizados',
      'class' => 'HS_Reportes_personalizados',
      'path' => 'modules/HS_Reportes_personalizados/HS_Reportes_personalizados.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/hs_facturador_proyectos_notes_HS_Facturador_proyectos.php',
      'to_module' => 'HS_Facturador_proyectos',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/hs_facturador_proyectos_notesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/HS_Facturador',
      'to' => 'modules/HS_Facturador',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/HS_Facturador_proyectos',
      'to' => 'modules/HS_Facturador_proyectos',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/HS_inventarios',
      'to' => 'modules/HS_inventarios',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/HS_Prestamos',
      'to' => 'modules/HS_Prestamos',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/HS_Programador',
      'to' => 'modules/HS_Programador',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/HS_Registro_horas',
      'to' => 'modules/HS_Registro_horas',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/HS_Reportes_personalizados',
      'to' => 'modules/HS_Reportes_personalizados',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/HS_Facturador_proyectos.php',
      'to_module' => 'HS_Facturador_proyectos',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/HS_Facturador_proyectos.php',
      'to_module' => 'HS_Facturador_proyectos',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/hs_facturador_proyectos_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/hs_facturador_proyectos_notes_HS_Facturador_proyectos.php',
      'to_module' => 'HS_Facturador_proyectos',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'hs_facturador_proyectos_notes_name',
      ),
    ),
  ),
);