<?php
$dictionary['Project']['fields']['dias_corte_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Días de corte',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'dias_corte_c',
    'vname' => 'LBL_DIAS_CORTE',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'hs_dias_corte',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'Projectdias_corte_c',
);
