<?php
$dictionary['Project']['fields']['hora_entrada_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Hora entrada',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'hora_entrada_c',
    'vname' => 'LBL_HORA_ENTRADA',
    'type' => 'datetimecombo',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
    'display_default' => 'now&12:00am',
    'id' => 'Projecthora_entrada_c',
);

