<?php
$dictionary['Project']['fields']['max_pago_horas_viaje_proyect_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Máximo pago horas viaje proyecto',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'max_pago_horas_viaje_proyect_c',
    'vname' => 'LBL_MAX_PAGO_HORAS_VIAJE_PROYECT',
    'type' => 'decimal',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => 'Esto es lo maximo que paga el proyecto por horas de viaje ',
    'help' => 'Esto es lo maximo que paga el proyecto por horas de viaje ',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '3',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => '1',
    'id' => 'Projectmax_pago_horas_viaje_proyect_c',
   // 'custom_module' => 'Project',
);

