<?php
$dictionary['Project']['fields']['mostrar_dirrecion_en_factura_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Mostrar dirección en factura',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'mostrar_dirrecion_en_factura_c',
    'vname' => 'LBL_MOSTRAR_DIRRECION_EN_FACTURA',
    'type' => 'bool',
    'massupdate' => '0',
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id' => 'Projectmostrar_dirrecion_en_factura_c',
    // 'custom_module' => 'Project',
);