<?php
$dictionary['Project']['fields']['pagos_extra_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Pagos extra',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'pagos_extra_c',
    'vname' => 'LBL_PAGOS_EXTRA',
    'type' => 'multienum',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'hs_pagos_extra',
    'studio' => 'visible',
    'isMultiSelect' => true,
    'id' => 'Projectpagos_extra_c',
);