<?php
$dictionary['Project']['fields']['tipo_cobro_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Tipo cobro',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'tipo_cobro_c',
    'vname' => 'LBL_TIPO_COBRO',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'hs_tipo_cobro',
    'studio' => 'visible',
    'dependency' => false,
    'id' => 'Projecttipo_cobro_c',
);
