<?php
$dictionary['User']['fields']['puesto_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Puesto',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'puesto_c',
    'vname' => 'LBL_PUESTO',
    'type' => 'enum',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'hs_valores_pagar',
    'dependency' => false,
    'id' => 'Userspuesto_c',
);