
<?php
$dictionary['User']['fields']['valor_hora_c'] = array(
    'inline_edit' => '',
    'labelValue' => 'Valor hora',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'valor_hora_c',
    'vname' => 'LBL_VALOR_HORA',
    'type' => 'currency',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '26',
    'size' => '20',
    'precision' => 6,
    'id' => 'Usersvalor_hora_c',
);
