<?php
$dictionary['Account']['fields']['contacto_facturacion_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Contacto',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'contacto_facturacion_c',
    'vname' => 'LBL_CONTACTO_FACTURACION',
    'type' => 'varchar',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id' => 'Accountscontacto_facturacion_c',
   // 'custom_module' => 'Accounts',
);