<?php
$dictionary['Account']['fields']['fecha_vinculacion_c'] = array (
    'inline_edit' => '',
    'labelValue' => 'Fecha de  vinculación',
    'required' => true,
    'source' => 'custom_fields',
    'name' => 'fecha_vinculacion_c',
    'vname' => 'LBL_FECHA_VINCULACION',
    'type' => 'date',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'id' => 'Accountsfecha_vinculacion_c',
   // 'custom_module' => 'Accounts',
);