<?php
$dictionary['Case']['fields']['causa_c'] = array (
      'inline_edit' => '',
      'labelValue' => 'causas',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'causa_c',
      'vname' => 'LBL_CAUSAS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'Casescausa_c',
);