<?php
$dictionary['Case']['fields']['fecha_rechazo_aditoria_c'] = array (
    'inline_edit' => '1',
    'labelValue' => 'Fecha rechazo auditoría',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'fecha_rechazo_aditoria_c',
    'vname' => 'LBL_FECHA_RECHAZO_ADITORIA_C',
    'type' => 'datetimecombo',
    'massupdate' => '0',
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
    'id' => 'Casesfecha_rechazo_aditoria_c',
   // 'custom_module' => 'Cases',
);