<?php
$dictionary['Case']['fields']['rechazo_auditoria_c'] =  array (
    'inline_edit' => '1',
    'labelValue' => 'Rechazo auditoria',
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'rechazo_auditoria_c',
    'vname' => 'LBL_RECHAZO_AUDITORIA_C',
    'type' => 'bool',
    'massupdate' => '0',
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
 //   'len' => '255',
    'size' => '20',
    'id' => 'Casesrechazo_auditoria_c',
    //'custom_module' => 'Cases',
);