<?php
$dictionary['Case']['fields']['user_id1_c'] = array (
    'inline_edit' => 1,
    'required' => false,
    'source' => 'custom_fields',
    'name' => 'user_id1_c',
    'vname' => 'LBL_USUARIO_RECHAZO_AUDITORIA_C_USER_ID',
    'type' => 'id',
    'massupdate' => '0',
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '36',
    'size' => '20',
    'id' => 'Casesuser_id1_c',
  //  'custom_module' => 'Cases',
);
$dictionary['Case']['fields']['usuario_rechazo_auditoria_c'] = array (
  'inline_edit' => '1',
  'labelValue' => 'Usuario rechazo auditoría',
  'required' => false,
  'source' => 'non-db',
  'name' => 'usuario_rechazo_auditoria_c',
  'vname' => 'LBL_USUARIO_RECHAZO_AUDITORIA_C',
  'type' => 'relate',
  'massupdate' => '0',
  'default' => NULL,
  'no_default' => false,
  'comments' => '',
  'help' => '',
  'importable' => 'true',
  'duplicate_merge' => 'disabled',
  'duplicate_merge_dom_value' => '0',
  'audited' => true,
  'reportable' => true,
  'unified_search' => false,
  'merge_filter' => 'disabled',
  'len' => '255',
  'size' => '20',
  'id_name' => 'user_id1_c',
  'ext2' => 'Users',
  'module' => 'Users',
  'rname' => 'name',
  'quicksearch' => 'enabled',
  'studio' => 'visible',
  'id' => 'Casesusuario_rechazo_auditoria_c',
 // 'custom_module' => 'Cases',
);


